spring.application.name=Parking


spring.datasource.url=jdbc:postgresql://localhost:5432/smartparking
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# =========================
# RESILIENCE4J RETRY
# =========================

resilience4j.retry.instances.iaRetry.max-attempts=3
resilience4j.retry.instances.iaRetry.wait-duration=1s
app.admin.password=${ADMIN_PASSWORD}
app.jwt.secret=${JWT_SECRET}

# =========================
# CIRCUIT BREAKER
# =========================

resilience4j.circuitbreaker.instances.iaCircuit.failure-rate-threshold=50

resilience4j.circuitbreaker.instances.iaCircuit.sliding-window-size=5

resilience4j.circuitbreaker.instances.iaCircuit.minimum-number-of-calls=3

# =========================
# SWAGGER
# =========================

springdoc.swagger-ui.path=/swagger-ui.html